from typing import Any, Dict, List, Optional
from pydantic import BaseModel


class Stage(BaseModel):
    """A single stage in the LLM-planned workflow."""

    id: str
    reads: List[str] = []
    writes: List[str]
    prompt_template: str
    output_schema: Dict[str, Any]


class Plan(BaseModel):
    """Complete execution plan generated by the LLM."""

    stages: List[Stage]
    final_key: Optional[str] = None
